### PR TITLE
wayland_backend: round surface size towards infinity

### LINKED ISSUE #1329: Gamescope tries to set viewport source and destination to empty rectangle
```
[1107540.395] xdg_toplevel@53.configure(0, 0, array[16])
[1107540.397] xdg_surface@52.configure(2)
[...]
[1107580.834]  -> wp_viewport@46.set_source(0.00000000, 0.00000000, 0.00000000, 0.00000000)
[1107580.836]  -> wp_viewport@46.set_destination(0, 0)
[...]
[1107580.930] wl_display@1.error(wl_display@1, 3, "An error occurred while processing a request: Could not process a `wp_viewport.set_source` request: Rectangle is empty or outside the first quadrant")
```

### PR DESCRIPTION
**Pull request by mahkoh**
Otherwise, if the scale is larger than the texture size, the surface size would be 0.

Closes #1329

### CODE REVIEW

**Comment by Joshua-Ashton** [comment]
Surely you'd actually want:
```cpp
.nDstWidth   = int32_t( ( pLayer->tex->width() / double( pLayer->scale.x ) ) + 0.5 ),
.nDstHeight  = int32_t( ( pLayer->tex->height() / double( pLayer->scale.y ) ) + 0.5 ),
```

**Comment by Joshua-Ashton** [comment]
Hm, maybe ceil has this guarantee? ` Rounds x upward, returning the smallest integral value that is not less than x.`

**Comment by mahkoh** [comment]
Rounding halfway up is not sufficient. In the actual case that causes the crash

```
pLayer->tex->width() == 500
pLayer->scale.x = 1280
```

>if ceil gave you 1.99999999, you'd still round down.

ceil never returns 1.9999999 because 2 can be represented in an f32.

**Comment by Joshua-Ashton** [comment]
Sure, just thinking about numbers that aren't representable... but I don't think it matters much given everything could here.

**Pull request merged**
