### PR TITLE
VkDeviceOverrides::QueuePresentKHR(): reduce overhead

### PR DESCRIPTION
**Pull request by sharkautarch**
Gamescope WSI: VkDeviceOverrides::QueuePresentKHR(): reduce overhead of calling canBypassXWayland()

canBypassXWayland() sends and waits on xcb requests multiple times, each time it is called.

This is fine for most uses, but VkDeviceOverrides::QueuePresentKHR is run for each frame for the entire runtime, and it seems that the biggest hotspot within it, is the call to canBypassXWayland()

gamescope_wsi_layer_vtune_profiling_result_before_optimization
^ ```flamegraph from running `gamescope -- vkmark` (note: gamescope built from commit [14a1db3](https://github.com/sharkautarch/gamescope/commit/14a1db3a57612e5cfbba6d4c19688eafdc6c4043) )```

For most of the runtime, canBypassXWayland()  should usually return the same value, so the previous results can just be re-used, as long as the states of all of the windows hasn't changed
gamescope_wsi_layer_vtune_profiling_result_after_optimization
^ ```flamegraph from running same cmd, gamescope built w/ this PR```

**important note:**
This PR currently seems to mostly work, *except* that `eventWatcher()`  currently just checks for events on the root window, though I think resize/expose events should usually propagate up to the root window (not sure on this one).

### CODE REVIEW

**Comment by Joshua-Ashton** [comment]
I don't think they will get propagated like this. I think perhaps it makes sense for us to only do this on acquire and make present totally non-blocking.

How long is stuff taking time wise?

**Comment by Joshua-Ashton** [comment]
Perhaps we can have the listener listen for any changes at all and just dirty everything.

**Comment by Joshua-Ashton** [comment]
I removed a superfluous call just now also

**Comment by Joshua-Ashton** [comment]
I'm not confident you can watch for events like that across threads? What if the app is already doing that with this xcb connection?

**Comment by sharkautarch** [comment]
> How long is stuff taking time wise?

(keep in mind that I always filter out the initial setup-portion of the profiler data to make sure the analysis reflects the actual runtime)
Looking again at the flamegraph for *just* the vkmark process, vtune reports that 12.444 seconds of cputime is spent inside `GamescopeWSILayer::GamescopeSurfaceData::canBypassXWayland` out of a total 23.873 seconds of cputime measured for the entire vkmark process
 
Note that I believe that the cputime vtune reports doesn't exactly map to actual elapsed time. ( it measures both active and idle time, tho it might work the way CLOCK_PROCESS_CPUTIME_ID for clock_gettime works, where active time is measured to be longer than idle time...)
 
However, I definitely saw a noticable average FPS boost for vkmark w/ this PR across multiple runs. 
Definitely at least 100 or 200 more fps overall!

> I'm not confident you can watch for events like that across threads? What if the app is already doing that with this xcb connection?

judging from the documentation about `xcb_get_window_attributes_reply_t` that I found here:
https://www.mankier.com/3/xcb_get_window_attributes#Reply_Fields
it seems like multiple threads/processes can listen for the same events on the same window

> I don't think they will get propagated like this. I think perhaps it makes sense for us to only do this on acquire and make present totally non-blocking.

judging from the documentation about `xcb_change_window_attributes` that I found here:
https://www.mankier.com/3/xcb_change_window_attributes

Implied by the information about the `XCB_CW_DONT_PROPAGATE` mask:
` The do-not-propagate-mask defines which events should not be propagated to ancestor windows when no client has the event type selected in this window.` 

That seems to imply that events in child windows that aren't registered will be propagated to their parent window by default
Though of course, that also means that if an app has put the expose or resize mask in the dont propagate field, then events on that window are currently unaccounted for.

However, it seems like `xcb_wait_for_event` listens for events on the *entire* connection, so we could simply register resize/expose mask on all child windows and that should work fine, unless new windows are added later...
In which case, we could do `xcb_poll_for_event`, and if it returns NULL, we check for new child windows, and register resize/expose mask on those new windows, then afterwards sleep for certain amount of time...

**Comment by sharkautarch** [comment]
Hmmm now that I’ve looked through the limited amount of documentation out there, I think I might need to use the xcb-record extension (through the libXtst library)…

**Comment by ishitatsuyuki** [comment]
The overhead in QueuePresent is not nice, but unless you're running something at 1000fps this isn't going to be a bottleneck. The check is done *after* the present is submitted, so it doesn't affect end-to-end latency either. For starters, DXVK and VKD3D has dedicated thread doing submissions, so the cost of check is most of the time unlikely to show up even the slightiest in any metric.

I think the function only appears "hot" because you're profiling a thread that is mostly idle.

The current check is just 4 lines of code. Replacing this with a convoluted solution isn't going to happen without significant justification.

**Comment by sharkautarch** [comment]
I will re-evaluate this later

**Pull request closed without merging**
