### PR TITLE
vblankmanager: Port to timerfd

### PR DESCRIPTION
**Pull request by Joshua-Ashton**
Ports vblankmanager to be timerfd based, and also fxies issues
with re-arming at higher refresh rates.

The old nudge thread method still exists (and is needed for VR), and
it has also been improved to fix the re-arming issue.

The old method can be enabled with GAMESCOPE_DISABLE_TIMERFD.

This additionally ports the main poll event loop to epoll with the new waitable system and fixes a presentWaitID bug in Vulkan.

cc: @sharkautarch Probably interests you?

### CODE REVIEW

**Comment by Joshua-Ashton** [comment]
Thoughts:

Because we are using timerfd, ulWakeupTime should actually be the target point from the timerfd when using that, not the point from OnPollIn, so we can account for the scheduling quantums from the target wakeup time and other work (like we were wrt the pipe write before)

**Comment by Joshua-Ashton** [comment]
Seems like there is some unstable frametiming introduced by:
```
commit 46bbf7214ca99a2df13df3de569eb6016e5eeb05
Author: Joshua Ashton <joshua@froggi.es>
Date:   Wed Dec 6 22:51:33 2023 +0000

    steamcompmgr: Move main poll event loop to new waitable system
```

Not sure why yet...

**Comment by Joshua-Ashton** [comment]
Fixed that, it was because nudge_steamcompmgr was not nudging the new FD on the g_SteamCompMgrWaiter but the old global nudge one that is now unused.

**Comment by sharkautarch** [comment]
>cc: @sharkautarch Probably interests you?


I merged this PR into my own branch `nvidia-fix-vblank-timerfd`
Initial testing w/ vkcube: works well when running w/ ENABLE_GAMESCOPE_WSI=1, but stutters with ENABLE_GAMESCOPE_WSI=0

**Comment by Joshua-Ashton** [comment]
If you are testing on NVIDIA I am not surprised at there being issues without WSI given the whole xserver interaction there.

**Pull request merged**
