### PR TITLE
Hook up optional tracy profiler integration

### PR DESCRIPTION
**Pull request by sharkautarch**
Shouldn't add any runtime overhead when compiling gamescope w/ tracy disabled  (the default)

Advantage of profiling w/ Tracy compared to other sampling profilers is that Tracy's profiling info is way more precise, and Tracy can track slowdowns for (an) individual [delayed] frame(s).

In the current state of this PR, when compiling gamescope w/ tracy enabled, instruments some places with `ZoneScoped`. profiles frame timings w/ `FrameMarkStart/FrameMarkEnd`

Also has a default-disabled option (`tracy_collect_callstacks`) for collecting callstacks in some places: `paint_all()` and `xwayland_ctx_t::Dispatch`
I might add additional places to optionally collect callstacks from in the future...

Next Tracy TODO will be to hook up Tracy's vulkan profiling stuff...
(also sorry about the two closed PRs I made accidentily... I had done a `git push -f` after forgetting to first do `git commit`...)

### CODE REVIEW

**Comment by sharkautarch** [comment]
**UPDATE**:
I have now hooked up tracy's vulkan profiling:
gamescope_tracy_vulkan_screenshot

**Comment by matte-schwartz** [comment]
@sharkautarch I've got your tracy_profiling branch merged into master and set up on my dev rig. Gamescope integration seems pretty solid so far, nice work.

I still need to figure out how to make heads or tails of what I see in there, along with setting it up remotely so I can capture drm backend tracing live but that's just a skill issue on my end... time to read the docs.

**Comment by sharkautarch** [comment]
@matte-schwartz 
For testing drm backend, since it’d be awkward to try to have gamescope *and* the profiler gui up on the same device
I suggest you build gamescope w/ meson flags: `-Dtracy_only_localhost=false -Dtracy_enable=true`
Then you should be able to run the Tracy profiler on another device, capturing the stats over the network.
I’m not entirely sure if you’ll need to change any firewall settings.
The profiler gui is designed so that it’s technically a server that the async profiling code in gamescope will connect to, so you might not need to change any firewall settings on your steam deck. 
again, I’m not entirely sure. I’ve only tested running gamescope (nested/desktop mode) + the profiler gui on the same device…

**Comment by sharkautarch** [comment]
@matte-schwartz 
I added a new commit that records gamescopectl commands w/ tracy.
It actually logs the command *before* the command executes, which means that you'll always see the effects of a command at some point after wherever the message shows up in tracy profiler gui.
Note that you can search for messages by clicking on the messages button at the top of the gui, and then typing the command (ex: `adaptive_sync`) into the box next to where it says `Filter messages`

I made sure that when you do something like `gamescopectl adaptive_sync 0`, tracy logs `adaptive_sync 0`, and not just `adaptive_sync`

**Comment by matte-schwartz** [comment]
Seems like tracy profiling may introduce some instability within gamescope-session, not sure if it's from the profiler running out of memory or something like that, but it only happened while I was hammering gamescope with continuous rendering + full mangohud for an extended period of time with tracy profiling connected remotely.

Journal logs of the crash + backtrace of the coredump w/ each thread:
[tracy-gamescope-coredump.log](https://github.com/user-attachments/files/16327351/tracy-gamescope-coredump.log)

**Comment by sharkautarch** [comment]
Oh I think the crash might be due to weirdness w/ static variables, and/or maybe a race condition
I’ll see if I can fix it soon…
Definitely a rare edgecase scenario

**Comment by sharkautarch** [comment]
@matte-schwartz 
Just pushed out a commit that may fix the issue, tho I'm not entirely sure if it *actually* fixes it...

**Pull request closed without merging**
