### PR TITLE
Add --version and separate dependency installation into script

### PR DESCRIPTION
**Pull request by safijari**
This PR adds a way to encode the current "version" into the gamescope binary. The version comes from a `git describe` command and looks like: `3.12.1-133-gb4af6e3-dirty` where the first part is the nearest tag, the short git hash is added after the `-g` and if any files in the git repo have been changed but not committed the `-dirty` flag is added. There's also a way to inject a version by setting the `GAMESCOPE_VERSION` environment variable prior to the build, and if the folder isn't a git repo and this variable is not set then calling `--version` prints out a message telling the user to check the version using their distro's package manager.

This is done by creating a "gamescope_version.h" file every time ninja is called. This has the small downside that even with no changes _some_ compilation will happen. I'm looking for ways to eliminate this when the .h file has not changed.

Also the dependency installation step has been put into its own script.

Some of this stuff I can't fully test because I don't know how the actual builds are done.

### CODE REVIEW

**Comment by emersion** [comment]
I don't believe Git is a reliable way to get the version. Distros usually build from tarballs.

**Comment by safijari** [comment]
https://gitlab.archlinux.org/archlinux/packaging/packages/gamescope/-/blob/main/PKGBUILD?ref_type=heads#L74

Arch is using git at least. I can dig into some others.

Point taken though. At the very least there should be a fallback for distro builds that tell the user to check their package manager.

**Comment by safijari** [comment]
> I don't believe Git is a reliable way to get the version. Distros usually build from tarballs.

I have added a way to inject the version using an environment variable as well as a fallback message in case version cannot be determined.

**Comment by q66** [comment]
i also don't think it's reasonable to pointlessly introduce build-time dependency on bash because of a trivial shell script that wouldn't look any different with plain /bin/sh

**Comment by safijari** [comment]
> i also don't think it's reasonable to pointlessly introduce build-time dependency on bash because of a trivial shell script that wouldn't look any different with plain /bin/sh

"Please use sh instead of bash"

Sounds good.

**Comment by safijari** [comment]
@emersion any thoughts after the changes?

Would like to understand if the PR just needs more work or if it has no chance of ever being accepted.

**Pull request closed without merging**
