### PR TITLE
Add support for the explicit sync protocol

### PR DESCRIPTION
**Pull request by emersion**
See https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/90  
wlroots MR: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4262

### CODE REVIEW

**Comment by GloriousEggroll** [comment]
can we get a rebase of this? it doesn't apply on top of current main

**Comment by RyzenDew** [comment]
?will this be updated soon?

**Comment by Joshua-Ashton** [comment]
Superceded

**Comment by ioquatix** [comment]
Superceded by what?

**Comment by edisionnano** [comment]
> Superceded by what?

https://github.com/ValveSoftware/gamescope/pull/1203

**Pull request closed without merging**
