### PR TITLE
Rendervulkan.cpp: Use less conservative (memory and execution) barriers

### PR DESCRIPTION
**Pull request by sharkautarch**
This PR tries to optimize barrier usage w/ shaders by getting ahead-of-time information of the shader usage pattern in vulkan_composite()

I've tested this PR for syncronization hazards w/ the Vulkan Validation Layer's sync + queueSubmit() validation.
The only sync hazard it showed was a Present-After-Write around vkQueuePresentKHR that is also detected w/ ValveSoftware/gamescope/master (not sure if it is a false positive or is a real issue...).

~~I will note that I had to force `.oldLayout` for shaders to be `VK_IMAGE_LAYOUT_GENERAL` instead of `VK_IMAGE_LAYOUT_UNDEFINED`, because the validation layers would report sync hazards from what it detects is a layout transition from undefined -> general...~~
EDIT: fixed the issue mentioned in the crossed out part

### CODE REVIEW

**Comment by Joshua-Ashton** [comment]
I really dislike the idea of encoding certain task types. We should probably make this more akin to a proper render graph.

**Comment by sharkautarch** [comment]
> I really dislike the idea of encoding certain task types. We should probably make this more akin to a proper render graph.


uhh yeah I guess...
I mean gamescope's compute shaders mostly just execute one after the other, so the most use out of this PR is to remove unnecessary parts of memory barrier.
Tho I guess that a rendergraph would be more useful w/ the barriers around reshade...
I'm sure someone will figure that part out at some point

**Comment by sharkautarch** [comment]
> I really dislike the idea of encoding certain task types. We should probably make this more akin to a proper render graph.


@Joshua-Ashton 
Now that I think about it, maybe a framegraph would be better for gamescope than a rendergraph
Unfortunately, the only open source implementation of a framegraph that I could find is this archived one: https://github.com/azhirnov/FrameGraph

**Comment by sharkautarch** [comment]
Going to close this, since it is clear that a rendergraph-based syncronization approach is what's desired.
I might look into hooking up Vuk rendergraph into gamescope in the future

**Pull request closed without merging**
