### PR TITLE
use latest upstream wlroots

### PR DESCRIPTION
**Pull request by sharkautarch**
Fixes issue #1364

from testing on an x11 host,
This pr works fine ~~, BUT:~~
~~when merged w/ the master branch, and running `build/sec/gamescope -- glxgears` the graphics looked glitchy (no clue what’s causing this)~~

~~I double checked running said command for~~
~~- this pr (branch `newer_wlroots`)~~
~~- branch master (without this pr)~~
~~Didn’t encounter any issue for the two above cases…~~
After re-building gamescope and testing again, I no longer encountered any issues

### CODE REVIEW

**Comment by matte-schwartz** [comment]
I'll give it a test on Wayland DEs and in Gamescope-session with a few different devices and see if I find any clues for you.

**Comment by matte-schwartz** [comment]
merged into tag 3.14.21 to avoid merge conflicts. No new regressions to note yet on Wayland desktop (Plasma 6.1) or Gamescope-session with the Wayland backend. Tested on both my OLED Deck and my 7900xtx laptop. 

I wasn't able to repro any aritfacts with glxgears, perhaps limited to X11? Only artifacting present for me is the exact same as I've reported previously with explicit sync and mangohud.

**Comment by sharkautarch** [comment]
> merged into tag 3.14.21 to avoid merge conflicts. No new regressions to note yet on Wayland desktop (Plasma 6.1) or Gamescope-session with the Wayland backend. Tested on both my OLED Deck and my 7900xtx laptop.
> 
> I wasn't able to repro any aritfacts with glxgears, perhaps limited to X11? Only artifacting present for me is the exact same as I've reported previously with explicit sync and mangohud.

It's possible
I could provide a branch w/ all the commits from master merged in just in case...

**Comment by sharkautarch** [comment]
@matte-schwartz 
Here's a branch w/ this PR merge w/ the master branch:
`newer_wlroots_merge_w_master`

**Comment by matte-schwartz** [comment]
Was gonna say, I've been running it all day and haven't found any new regressions even on x11. Maybe you had a bad older layer interfering or a bad EDID write or something? Who knows with Gamescope sometimes 🐸

**Comment by sharkautarch** [comment]
Upon reflection, I think I encountered the glitchy graphics because I had originally wrote the PR ontop of my `test_w_no_lut_newer` branch, and I had written some unrelated tweaks along with the changes in this PR. So I think I originally tested the PR + some unrelated changes. (Note that I reverted said unrelated changes in `test_w_no_lut_newer`, w/ the changes ‘archived’ in `test_w_no_lut_newer_bak`)

At the time, I didn’t think those unrelated changes were that crazy, so didn’t occur to me that they could be causing any issue…

Anyhow, everything is working fine now! :)

**Comment by Joshua-Ashton** [comment]
Thanks, I ended up merging this manually and adding you as a co-author =)

**Comment by sharkautarch** [comment]
@Joshua-Ashton 
there was an important nullptr check that was left out from this PR (which someone else confirmed that it was a necessary check)
See a new PR I made about it: https://github.com/ValveSoftware/gamescope/pull/1444

**Pull request closed without merging**
