### PR TITLE
Update AMD color management for Linux 6.8

### LINKED ISSUE #1006: Unstable refresh rate when VRR and HDR are enabled
Problem:

When running games via steam in gamescope in DRM mode with HDR and VRR enabled, the screen's refresh rate is very unstable and jumps between 61 and 120 instead of being consistent with the game's framerate. This results in visible stuttering instead of smooth gameplay.

My setup is:
- CPU: Ryzen 5700G
- GPU: Radeon 6700XT
- Kernel: 6.5.9-arch2 (although amd-drm-next exhibits the same problem) 
- Display: Samsung S95B TV, 3840x2160@120Hz (with chroma subsampling since AMD doesn't yet support HDMI 2.1, no idea if this is relevant at all)

Games tested:
- The Talos Principle 2
- Forza Horizon 4
- Doom Eternal

All of these run below the screen's native 120Hz refresh rate, mostly around 80-90FPS. I'm checking the TV's refresh rate via its builtin OSD, it's telling me that Freesync is enabled and the refresh rate is rapidly switching between 120 and 61. If a game is running at 120FPS stably, then the issue does not occur.

Interestingly, in Steam UI I don't see this problem, instead I see a stable 110 FPS and no stutter at all.

### PR DESCRIPTION
**Pull request by ajoneil**
With the 6.8 release of the kernel just around the corner, I've updated the AMD color management code paths to work with the stock kernel, for those adventurous enough to add `AMD_PRIVATE_COLOR` to `KCFLAGS`.

This fixes #1006 for me, on an RX 6800 XT.

### CODE REVIEW

**Comment by Joshua-Ashton** [comment]
Thanks, I will land this when I check everything works on the next SteamOS kernel

**Comment by Joshua-Ashton** [comment]
(that may be a little while fwiw)

**Comment by Joshua-Ashton** [comment]
i could add a fallback name to the property thing actually... ill look at doing that

**Comment by ajoneil** [comment]
> i could add a fallback name to the property thing actually... ill look at doing that

I think this'll be a tad more complex, as some of the enums have changed. If you haven't looked at this just yet, there's a chance I'll look into a bit more over the weekend. IIRC the goal is to eventually have a cross-vendor colour management API in the kernel, so having multiple strategies for interacting with the kernel will be beneficial in the long run to avoid having to compile gamescope specifically for whatever kernel API is available.

**Comment by Joshua-Ashton** [comment]
oh good point re the enum thing

**Comment by Lawstorant** [comment]
I still have issues even with this patch. Steam works correctly, even a game like Ori and the will of the wisps works great. But EA WRC/Grid 2019 immediately cause washed-out colors like there's inverse tone-mapping happening + color conversion to sRGB. If I quit the game and re-toggle HDR, it goes back to normal

**Comment by Lawstorant** [comment]
Hmm, maybe it's something in the driver. The washed out colors persisted even after going back to GDM. I'll try removing ppfeature mask from kernel cmdline

**Comment by ajoneil** [comment]
> Hmm, maybe it's something in the driver. The washed out colors persisted even after going back to GDM. I'll try removing ppfeature mask from kernel cmdline

I've noticed this as well, though I haven't dug into it too deeply. Does this only happen after running gamescope, or is it present after a fresh boot? Since a [recent refactor](https://github.com/ValveSoftware/gamescope/pull/1121/files#diff-452db373032f99b8c4bd2ed8b40bbd2bab7bed63bf8c51714acc025ea9b6200fL6407), there's a `finish_drm` function that's not currently being called to clean things up, so if it's only happening after running gamescope then it could be due to not cleaning up fully.

When my display gets into a weird state, triggering a hotplug usually fixes it for me:
`sudo bash -c "echo 1 > /sys/kernel/debug/dri/1/DP-1/trigger_hotplug"`

**Comment by Lawstorant** [comment]
Yeah, that fixes it when it happens BUT most games still can't be played as it seems like something breaks with color management. Ori is the only game that manages to play ok. Any other game break HDR (even if it's not HDR-capable itself) and inverse tone mapping breaks. I didn't have such problems with linux-neptune-65

**Comment by ajoneil** [comment]
I've seen similar issues to what you're describing when I first updated to Linux 6.8 (one of the RCs), but don't have the same issues with this patch. Sometimes I see an issue with my TV not using the right colour space when first loading gamescope/steam, but it almost always fixes itself if I navigate between games in the steam UI, and as I'm using a DP -> HDMI 2.1 adapter I'm not confident whether this issue stems from software or hardware.

 Just to confirm, are you using a v6.8 kernel that has been compiled with the experimental AMD colour properties enabled? These aren't enabled by default or even via a config option, only by a define. I'm not sure if gamescope gives a clear indicator whether it's using these properties or not.

**Comment by flibitijibibo** [comment]
For further testing I've made a Fedora 40 COPR that builds the kernel with AMD_PRIVATE_COLOR enabled, and applied this patch to the gamescope package: https://copr.fedorainfracloud.org/coprs/flibitijibibo/kernel-hdr-40/

If/when 39 gets 6.8 I'll push the same changes here: https://copr.fedorainfracloud.org/coprs/flibitijibibo/kernel-hdr/

**Comment by mkopec** [comment]
Same here, using the AUR packages from @ajoneil . In almost all games, switching focus from steam UI to the game causes colors to be washed out. Except for 2 games, Death Stranding and Ori and the Will of the Wisps.

I saw in gamescope logs that in those games `VK_COLOR_SPACE_HDR10_ST2084_EXT` colorspace is picked and some HDR metadata is printed in the logs, and in all other games `VK_COLOR_SPACE_SRGB_NONLINEAR_KHR` is picked. I'll try to provide some logs when I find a while

**Comment by Joshua-Ashton** [comment]
I think we probably need to diff what's going on in the upstream private AMD COLOR vs what we have on Deck. There might be some work missing there.

**Comment by anthr76** [comment]
I tried to give this patch a go against 3.14.2 but didn't have much luck. I'll attach a back trace

https://gist.github.com/anthr76/e1bc919bea3c790035790c93e2a9b446

**Comment by flibitijibibo** [comment]
> I tried to give this patch a go against 3.14.2 but didn't have much luck. I'll attach a back trace
> 
> https://gist.github.com/anthr76/e1bc919bea3c790035790c93e2a9b446

Was able to reproduce this with 3.14.2 and kernel 6.8 - after fussing with this for a while I was also able to make the same crash with 3.13.19 and kernel 6.7 with the VALVE1 HDR patchset, with the following change:

```diff
-       return drm->primary->has_color_mgmt;
+       return drm->primary->props.contains("VALVE1_PLANE_CTM");
```

The reason this is different is because this check was being done with a different property:

```
               plane->has_color_mgmt = plane->props.contains( "VALVE1_PLANE_BLEND_TF" );
```

Doing the same swap with the latest versions makes it go away, but it does highlight a problem that either the detection or the setting of color management isn't working... lines of interest from a modified gamescope with printf spam:

```
setting FB_ID: 151
setting zpos: 0
setting alpha: 65535
setting SRC_X: 0
setting SRC_Y: 0
setting SRC_W: 251658240
setting SRC_H: 141557760
setting rotation: 1
setting CRTC_X: 0
setting CRTC_Y: 0
setting CRTC_W: 3840
setting CRTC_H: 2160
setting AMD_PLANE_DEGAMMA_TF: 0
setting AMD_PLANE_SHAPER_LUT: 0
setting AMD_PLANE_SHAPER_TF: 0
setting AMD_PLANE_LUT3D: 0
setting AMD_PLANE_CTM: 0
setting AMD_PLANE_BLEND_TF: 0
setting AMD_PLANE_CTM: 0
setting FB_ID: 0
setting AMD_PLANE_DEGAMMA_TF: 0
setting AMD_PLANE_SHAPER_LUT: 0
setting AMD_PLANE_SHAPER_TF: 0
setting AMD_PLANE_LUT3D: 0
setting AMD_PLANE_BLEND_TF: 0
setting AMD_PLANE_CTM: 0
setting FB_ID: 0
setting AMD_PLANE_DEGAMMA_TF: 0
setting AMD_PLANE_SHAPER_LUT: 0
setting AMD_PLANE_SHAPER_TF: 0
setting AMD_PLANE_LUT3D: 0
setting AMD_PLANE_BLEND_TF: 0
setting AMD_PLANE_CTM: 0
setting FB_ID: 0
setting AMD_PLANE_DEGAMMA_TF: 0
setting AMD_PLANE_SHAPER_LUT: 0
setting AMD_PLANE_SHAPER_TF: 0
setting AMD_PLANE_LUT3D: 0
setting AMD_PLANE_BLEND_TF: 0
setting AMD_PLANE_CTM: 0
setting FB_ID: 0
setting AMD_PLANE_DEGAMMA_TF: 0
setting AMD_PLANE_SHAPER_LUT: 0
setting AMD_PLANE_SHAPER_TF: 0
setting AMD_PLANE_LUT3D: 0
setting AMD_PLANE_BLEND_TF: 0
setting AMD_PLANE_CTM: 0
setting FB_ID: 0
setting AMD_PLANE_DEGAMMA_TF: 0
setting AMD_PLANE_SHAPER_LUT: 0
setting AMD_PLANE_SHAPER_TF: 0
setting AMD_PLANE_LUT3D: 0
setting AMD_PLANE_BLEND_TF: 0
setting AMD_PLANE_CTM: 0
```

The AMD_PLANE/VALVE1_PLANE lines only show up when AMD_PLANE_CTM is detected, which is fine, but then liftoff comes back with this...

```
actually this one AMD_PLANE_BLEND_TF
 Layer 0x1dcb610 -> plane 72: incompatible properties
```
"Actually this one" just means it hit the end of this switch, meaning the property in the plane is missing even though it's in the plane:

https://gitlab.freedesktop.org/emersion/libliftoff/-/blob/master/plane.c?ref_type=heads#L400

I can't tell if this is an issue with gamescope's interaction with libliftoff, or if the property is actually missing from the drm plane, or what... I did notice that BLEND_TF is not always set, and on DCN 3.2 (which I think the 7900XTX has?) this bool is supposed to be false:

https://github.com/torvalds/linux/blob/master/drivers/gpu/drm/amd/display/amdgpu_dm/amdgpu_dm_plane.c#L1519

So there's _definitely_ a mismatch somewhere, but this isn't my usual territory so I'll have to defer to someone who knows what this stuff is really supposed to do.

**Comment by flibitijibibo** [comment]
On a whim I just wrapped the BLEND_TF set and things appear to work again (can't say if the colors are right or not though):

```diff
diff --git a/src/drm.cpp b/src/drm.cpp
index 29b8d06..bc4038f 100644
--- a/src/drm.cpp
+++ b/src/drm.cpp
@@ -2463,10 +2463,13 @@ drm_prepare_liftoff( struct drm_t *drm, const struct FrameInfo_t *frameInfo, boo
 
                        if ( drm_supports_color_mgmt( drm ) )
                        {
-                               if (!g_bDisableBlendTF && !bSinglePlane)
-                                       liftoff_layer_set_property( drm->lo_layers[ i ], "AMD_PLANE_BLEND_TF", drm->pending.output_tf );
-                               else
-                                       liftoff_layer_set_property( drm->lo_layers[ i ], "AMD_PLANE_BLEND_TF", AMDGPU_TRANSFER_FUNCTION_DEFAULT );
+                               if (drm->pPrimaryPlane->GetProperties().AMD_PLANE_BLEND_TF.has_value())
+                               {
+                                       if (!g_bDisableBlendTF && !bSinglePlane)
+                                               liftoff_layer_set_property( drm->lo_layers[ i ], "AMD_PLANE_BLEND_TF", drm->pending.output_tf );
+                                       else
+                                               liftoff_layer_set_property( drm->lo_layers[ i ], "AMD_PLANE_BLEND_TF", AMDGPU_TRANSFER_FUNCTION_DEFAULT );
+                               }
 
                                if (frameInfo->layers[i].ctm != nullptr)
                                        liftoff_layer_set_property( drm->lo_layers[ i ], "AMD_PLANE_CTM", frameInfo->layers[i].ctm->GetBlobValue() );
```

@Joshua-Ashton, this patch look okay? (Everyone else should probably avoid this patch until we know that it doesn't do anything horrible)

**Comment by Joshua-Ashton** [comment]
Is `AMD_PLANE_BLEND_TF` missing from upstream? We do kinda need that.

**Comment by flibitijibibo** [comment]
It's there but it's not always included as a property; 7900XTX for example does not have the bool set that gets the kernel to add it; this is true for both VALVE1 and AMD AFAICT.

**Comment by anthr76** [comment]
That's great @flibitijibibo can you share how you came to this conclusion so I can hopefully post more helpful reports in the future?

**Comment by Joshua-Ashton** [comment]
Does it work if you just set that cap to 1? :D

I find it hard to believe they would actually remove that functionality in hardware specifically for just dcn32 then none of the ones before/after/around... It doesn't make any sense...

**Comment by Joshua-Ashton** [comment]
I have a feeling that the author may have been confused between ogam ROM vs ogam RAM?

If that block is truly missing, well shit.

**Comment by Joshua-Ashton** [comment]
Thanks for looking into this btw

**Comment by flibitijibibo** [comment]
I can try to patch this in my COPR repo but it'll take 5 hours to build so I'll be able to test tomorrow at the earliest - is there someone at AMD that can confirm that this is the right check?

@anthr76 Found the line that printed an error and called abort with git grep, then added lots of printf spam deeper and deeper into the drm_prepare (the function that returned the error code) stack until I had enough keywords to grep around in the kernel source and see how the keyword worked. I would not recommend this strategy :P

**Comment by flibitijibibo** [comment]
Should have a test result in ~6 hours: https://copr.fedorainfracloud.org/coprs/flibitijibibo/kernel-hdr/build/7287031/

Looking at the git logs I think you're right that ogam_ram/rom got mixed up; the last commit to the resource files re: ogam was this, which flips the bit for newer hardware and doesn't really explain why, nor does it fix the bit for other versions (though the comment for 3.2 was updated):

https://github.com/torvalds/linux/commit/90f33674a0756a6f0907b8f6350cec3f7be4032c#diff-c8340b296cae499b96a64489d78906d34ef74f7d5872c625e2e8434a9339dc5d

**Comment by flibitijibibo** [comment]
Test results are in: Setting ogam_ram to 1 works just fine on a 7900XTX... so I guess we should let AMD know!

Can also confirm what others are seeing: In Steam the display recognizes an HDR signal, but a few seconds after the game window starts presenting it falls back to an SDR signal, happens with both SDR and HDR content. The swapchain image formats seem correct so I guess it's between the compositor and display engine, rather than any particular application and the compositor. Could composition in gamescope be causing this?

**Comment by Joshua-Ashton** [comment]
It is probably Steam turning off the HDR setting baseon its own preferences

**Comment by Joshua-Ashton** [comment]
@flibitijibibo Can you disable `cv_drm_single_plane_optimizations` and make sure it still works? Then either your or I can send a patch

**Comment by flibitijibibo** [comment]
Disabling the optimization still works. I don't have much experience submitting patches to the lkml, so if someone else does I can at least add a Tested-by line to it!

(Also, if there's a way to change Steam's HDR preference in non-SteamOS gamepadui I can test that as well)

**Comment by Joshua-Ashton** [comment]
Not sure there is a way -- really we need to move a lot of things from -steamos to being "inside gamescope"

**Comment by Joshua-Ashton** [comment]
I merged this by hand, accounting for BLEND_TF being broken

**Comment by anthr76** [comment]
I ended up trying @flibitijibibo 's kernel patch but sadly it moved the stack trace to the kernel

```
Apr 11 21:00:47 octo kernel: ------------[ cut here ]------------
Apr 11 21:00:47 octo kernel: WARNING: CPU: 8 PID: 186 at drivers/gpu/drm/amd/amdgpu/../display/dc/hwss/dcn32/dcn32_hwseq.c:499 dcn32_set_>
Apr 11 21:00:47 octo kernel: Modules linked in: snd_seq_dummy snd_hrtimer rfcomm snd_seq hid_microsoft ccm algif_aead crypto_null des3_ed>
Apr 11 21:00:47 octo kernel:  nft_compat legion_laptop soundcore k10temp i2c_piix4 gpio_amdpt platform_profile gpio_generic mac_hid nf_ta>
Apr 11 21:00:47 octo kernel: CPU: 8 PID: 186 Comm: kworker/u32:7 Tainted: G           OE      6.8.5-cachyos #1-NixOS 00000000000000000000>
Apr 11 21:00:47 octo kernel: Hardware name: ASUS System Product Name/ROG STRIX B650E-I GAMING WIFI, BIOS 2413 02/02/2024
Apr 11 21:00:47 octo kernel: Workqueue: events_unbound commit_work
Apr 11 21:00:47 octo kernel: RIP: 0010:dcn32_set_mcm_luts+0x11c/0x150 [amdgpu]
Apr 11 21:00:47 octo kernel: Code: 89 df 48 83 c6 04 5b 5d 48 8b 80 e0 00 00 00 41 5c 41 5d 41 5e ff e0 cc 66 90 cc 48 83 c7 10 eb 8b 48 >
Apr 11 21:00:47 octo kernel: RSP: 0018:ffffbe1900867948 EFLAGS: 00010246
Apr 11 21:00:47 octo kernel: RAX: 0000000000000001 RBX: ffff965315108000 RCX: 0000000000000000
Apr 11 21:00:47 octo kernel: RDX: 0000000000000000 RSI: ffff96531199c820 RDI: ffff965367348000
Apr 11 21:00:47 octo kernel: RBP: ffff96536de08800 R08: 0000000000000004 R09: ffffbe1900867880
Apr 11 21:00:47 octo kernel: R10: ffffbe1900867900 R11: 0000000000000001 R12: 0000000000000000
Apr 11 21:00:47 octo kernel: R13: ffff965315120000 R14: ffff965315120020 R15: 0000000000000000
Apr 11 21:00:47 octo kernel: FS:  0000000000000000(0000) GS:ffff965a5dc00000(0000) knlGS:0000000000000000
Apr 11 21:00:47 octo kernel: CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Apr 11 21:00:47 octo kernel: CR2: 000071ec350caf54 CR3: 0000000639620000 CR4: 0000000000f50ef0
Apr 11 21:00:47 octo kernel: PKRU: 55555554
Apr 11 21:00:47 octo kernel: Call Trace:
Apr 11 21:00:47 octo kernel:  <TASK>
Apr 11 21:00:47 octo kernel:  ? __warn+0x81/0x1b0
Apr 11 21:00:47 octo kernel:  ? dcn32_set_mcm_luts+0x11c/0x150 [amdgpu 0000000000000000000000000000000000000000]
Apr 11 21:00:47 octo kernel:  ? report_bug+0x202/0x270
Apr 11 21:00:47 octo kernel:  ? handle_bug+0x3c/0x80
Apr 11 21:00:47 octo kernel:  ? exc_invalid_op+0x19/0xc0
Apr 11 21:00:47 octo kernel:  ? asm_exc_invalid_op+0x1a/0x20
Apr 11 21:00:47 octo kernel:  ? dcn32_set_mcm_luts+0x11c/0x150 [amdgpu 0000000000000000000000000000000000000000]
Apr 11 21:00:47 octo kernel:  ? dcn32_set_mcm_luts+0x7c/0x150 [amdgpu 0000000000000000000000000000000000000000]
Apr 11 21:00:47 octo kernel:  dcn20_program_pipe+0x18b/0x680 [amdgpu 0000000000000000000000000000000000000000]
Apr 11 21:00:47 octo kernel:  dcn20_program_front_end_for_ctx+0x752/0xba0 [amdgpu 0000000000000000000000000000000000000000]
Apr 11 21:00:47 octo kernel:  commit_planes_for_stream+0x94a/0x26e0 [amdgpu 0000000000000000000000000000000000000000]
Apr 11 21:00:47 octo kernel:  ? srso_alias_return_thunk+0x5/0xfbef5
Apr 11 21:00:47 octo kernel:  dc_update_planes_and_stream+0x8a6/0x1630 [amdgpu 0000000000000000000000000000000000000000]
Apr 11 21:00:47 octo kernel:  ? optc1_get_crtc_scanoutpos+0x1/0x110 [amdgpu 0000000000000000000000000000000000000000]
Apr 11 21:00:47 octo kernel:  ? complete+0x1c/0x90
Apr 11 21:00:47 octo kernel:  amdgpu_dm_atomic_commit_tail+0x1c55/0x4070 [amdgpu 0000000000000000000000000000000000000000]
Apr 11 21:00:47 octo kernel:  commit_tail+0x91/0x130
Apr 11 21:00:47 octo kernel:  process_one_work+0x178/0x340
Apr 11 21:00:47 octo kernel:  worker_thread+0x301/0x490
Apr 11 21:00:47 octo kernel:  ? __pfx_worker_thread+0x10/0x10
Apr 11 21:00:47 octo kernel:  kthread+0xe5/0x120
Apr 11 21:00:47 octo kernel:  ? __pfx_kthread+0x10/0x10
Apr 11 21:00:47 octo kernel:  ret_from_fork+0x31/0x50
Apr 11 21:00:47 octo kernel:  ? __pfx_kthread+0x10/0x10
Apr 11 21:00:47 octo kernel:  ret_from_fork_asm+0x1b/0x30
Apr 11 21:00:47 octo kernel:  </TASK>
Apr 11 21:00:47 octo kernel: ---[ end trace 0000000000000000 ]---
```

**Comment by flibitijibibo** [comment]
Updating here since I don't think this was ever discussed elsewhere... the kernel patch was functional but DCN3.2 genuinely doesn't have ogam_ram, so the maintainers suggested checking for that version directly. I've been using this patch for some time now and it works okay, though I couldn't say if it'd pass review:

https://src.fedoraproject.org/fork/flibitijibibo/rpms/kernel/c/14fff133e0ba97ddbde3a73103b38abe4ab8fbf9?branch=f40

**Pull request closed without merging**
