### PR TITLE
Remove unused plane properties

### PR DESCRIPTION
**Pull request by ajoneil**
libliftoff is now responsible for setting plane properties, so almost all these properties are not used directly.

The remaining three are still in use, as libliftoff matches layers to planes but does not allow direct reading of properties.

This also includes #1164, as that uncalled function references these properties directly causing compiler errors.

### CODE REVIEW

**Comment by Joshua-Ashton** [comment]
I was interested in doing a non-liftoff path for Deck given it seemed to take a bunch of time and AMDGPU is a universal plane architecture on newer DCN, so it provides no benefit from what I can tell.

In general, the dead code probably exists for some reason, like your previous MR.

**Comment by emersion** [comment]
Why not improve libliftoff/amdgpu instead?

**Comment by Joshua-Ashton** [comment]
It would be cool to improve liftoff so it wasn't spamming strcmp for everything, etc, but I think it makes sense to have another path for modern AMD DCN.

We'd still keep that path around for other vendors.

**Comment by emersion** [comment]
That sounds like a step back in terms of pushing for fully generic user-space…

**Pull request closed without merging**
